# Generated by Django 2.0.8 on 2018-11-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('pictures', models.ImageField(null=True, upload_to='images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
