# Generated by Django 2.1.3 on 2018-11-24 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='css',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='javascript',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='python',
            field=models.BooleanField(default=False),
        ),
    ]
