# Generated by Django 2.1.3 on 2018-11-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=432, unique=True),
            preserve_default=False,
        ),
    ]
