# Generated by Django 2.1.3 on 2018-11-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20181124_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=435, unique=True),
            preserve_default=False,
        ),
    ]
