# Generated by Django 2.1.3 on 2018-11-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_suggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
