# Generated by Django 2.1.3 on 2018-11-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='link_to_book',
            field=models.URLField(unique=True),
        ),
    ]
