# Generated by Django 2.1.3 on 2018-11-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20181126_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
